name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  build-and-push-docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and tag Docker image
        env:
          MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
          AWS_DNS: ${{ secrets.AWS_DNS }}
          MONGODB_PORT: ${{ secrets.MONGODB_PORT }}
          MONGODB_NAME: ${{ secrets.MONGODB_NAME }}
        run: |
          # Build the Docker image
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/graphql-server:latest .
    
          # Also tag the image with the Git SHA for versioning
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/graphql-server:latest ${{ secrets.DOCKERHUB_USERNAME }}/graphql-server:${{ github.sha }}

      - name: Push Docker image to Docker Hub
        run: |
          # Push both tags to Docker Hub
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/graphql-server:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/graphql-server:${{ github.sha }}